title: Nurture The Couple - Massage for Two in Charleston SC
email: angela@charlestonscmassage.com 
description: >- # this means to ignore newlines until "baseurl:"
  Whether you're celebrating a special ocassion or simply treating yourself to an indulgent spa session, a couples massage is a great way for both you and your loved one to relax and rejuvenate.  Come get a couples in Charleston, SC.
# Build settings
markdown: kramdown
url: "charlestoncouplesmassage.com" 
github_username:  nurturemassage

image_path: 'assets/images/'
