backend:
  name: git-gateway
  branch: master 

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Page Title", name: "page-title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Menu Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Menu Visibility", name: "visible", widget: "boolean"}
      - {label: "Menu Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
